services:
  auth:
    image: powerdns/pdns-auth-master:latest
    container_name: pdns-auth
    environment:
      - PDNS_AUTH_API_KEY
      - PDNS_WEBSERVER_PASSWORD
    networks:
      net:
        ipv4_address: 172.18.0.3
    ports:
      - "8081:8081"
    volumes:
      - powerdns:/var/lib/powerdns
      - ./pdns-auth.d/pdns.conf:/etc/powerdns/pdns.d/pdns.conf
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'

  admin:
    image: powerdnsadmin/pda-legacy:latest
    container_name: pdns-admin
    networks:
      net:
    ports:
      - "80:80"
    volumes:
      - powerdnsadmin-data:/data
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'

  recursor:
    image: powerdns/pdns-recursor-master
    container_name: pdns-recursor
    networks:
      net:
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - ./recursor.d/pdns-recursor.conf:/etc/powerdns/recursor.d/pdns-recursor.conf
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'

volumes:
  powerdns:
    driver: local

  powerdnsadmin-data:
    driver: local

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
